openapi: 3.0.3
info:
  title: Interoperability APIs - Locations
  x-logo:
    url: "https://spdci.github.io/api-documentation/draft/dci-logo.png"
    backgroundColor: "#FFFFFF"
    altText: "Digital Convergence Initiative"
  description: Provide the location structure tree of the CRVS system
  version: 1.0.0
  contact:
    name: DCI Social Protection
    email: info@spdci.org
  license:
    name: DCI Social Protection License
    url: https://github.com/spdci/standards/blob/draft/LICENSE.md
servers:
  - url: "https://sandbox.spdci.org/namespace/v1.0.0"
    description: Sandbox Server
paths:
  /.well-known/locations.json:
    get:
      summary: "Locations : /.well-known/locations.json"
      description: "This endpoint can be used to build a location tree of the CRVS system or to find a specific location details"
      operationId: get_locations_json
      responses:
        "200":
          description: "Locations response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationsResponse"
        "404":
          $ref: "#/components/responses/HttpErrorResponse"
        "500":
          $ref: "#/components/responses/HttpErrorResponse"
      deprecated: false
components:
  schemas:
    LocationsResponse:
      $ref: schema/core/LocationsResponse.yaml
  responses:
    HttpErrorResponse:
      $ref: "../common/response/HttpErrorResponse.yaml"
